ffmpeg -i enemyshoot.wav -acodec pcm_s16le enemyshoot_.wav
ffmpeg -i exp.wav -acodec pcm_s16le exp_.wav
ffmpeg -i exp2.wav -acodec pcm_s16le exp2_.wav
ffmpeg -i heal.wav -acodec pcm_s16le heal_.wav
ffmpeg -i hit2.wav -acodec pcm_s16le hit2_.wav
ffmpeg -i shoot.wav -acodec pcm_s16le shoot_.wav
ffmpeg -i playerexp.wav -acodec pcm_s16le playerexp_.wav
ffmpeg -i playerhit.wav -acodec pcm_s16le playerhit_.wav
ffmpeg -i hitwall.wav -acodec pcm_s16le hitwall_.wav
ffmpeg -i spawn.wav -acodec pcm_s16le spawn_.wav
ffmpeg -i bounce.wav -acodec pcm_s16le bounce_.wav
ffmpeg -i hmm.wav -acodec pcm_s16le hmm_.wav